"""Write docs/models-and-entities.md from the integration's own tables.

The supported models and which entities each family gets are read from the
code, so the documentation cannot drift from what the integration does. A test
fails when the committed file is out of date. Regenerate it with:

    python -m script.generate_docs
"""

from collections.abc import Iterable
import json
from pathlib import Path

from custom_components.sungrow_modbus import (
    binary_sensor,
    button,
    number,
    select,
    sensor,
    switch,
)
from custom_components.sungrow_modbus.entity import SungrowModbusEntityDescription
from custom_components.sungrow_modbus.models import MODELS, Family, InverterModel

ROOT = Path(__file__).parent.parent
OUTPUT = ROOT / "docs" / "models-and-entities.md"
TRANSLATIONS = ROOT / "custom_components" / "sungrow_modbus" / "translations"

FAMILIES = (Family.K, Family.RS, Family.RT, Family.T, Family.MG)

PLATFORMS: tuple[tuple[str, str, Iterable[SungrowModbusEntityDescription]], ...] = (
    ("sensor", "Sensors", sensor.SENSORS),
    ("binary_sensor", "Binary sensors", binary_sensor.BINARY_SENSORS),
    ("select", "Selects", (*select.PRESET_SELECTS, *select.SELECTS)),
    ("number", "Numbers", number.NUMBERS),
    ("switch", "Switches", switch.SWITCHES),
    ("button", "Buttons", button.BUTTONS),
)

HEADER = """\
# Models and entities

<!-- Generated by `python -m script.generate_docs` from the integration's code. Do not edit. -->

Which Sungrow models the integration knows, and which entities each family
gets. An inverter reporting a device type code that is not listed here is set
up read-only: the sensors and binary sensors marked for RT, and no controls.
See [Supported inverters](supported-inverters.md) for what the families have
in common and where they differ.
"""


def _models_by_family() -> dict[Family, list[tuple[int, InverterModel]]]:
    by_family: dict[Family, list[tuple[int, InverterModel]]] = {
        family: [] for family in FAMILIES
    }
    for code, model in sorted(MODELS.items()):
        by_family[model.family].append((code, model))
    return by_family


def _model_table() -> list[str]:
    lines = [
        "## Models",
        "",
        "| Model | Device type code | Family | Phases | MPPTs |",
        "|---|---|---|---|---|",
    ]
    for family, models in _models_by_family().items():
        lines.extend(
            f"| {model.name} | 0x{code:04X} | {family} "
            f"| {3 if model.three_phase else 1} | {model.mppt_count} |"
            for code, model in models
        )
    return lines


def _support(description: SungrowModbusEntityDescription, family: Family) -> str:
    """Return whether every, some or no model of a family gets the entity."""
    models = [model for _, model in _models_by_family()[family]]
    having = [model.name for model in models if description.exists_fn(model)]
    if len(having) == len(models):
        return "✓"
    if not having:
        return "\N{EN DASH}"
    return ", ".join(having)


def _entity_table(
    platform: str, title: str, descriptions: Iterable[SungrowModbusEntityDescription]
) -> list[str]:
    names = json.loads((TRANSLATIONS / "en.json").read_text())["entity"][platform]
    lines = [
        f"### {title}",
        "",
        "| Name | Unit | Off by default | " + " | ".join(FAMILIES) + " |",
        "|---|---|---|" + "---|" * len(FAMILIES),
    ]
    for description in descriptions:
        unit = getattr(description, "native_unit_of_measurement", None) or ""
        off = "" if description.entity_registry_enabled_default else "yes"
        cells = " | ".join(_support(description, family) for family in FAMILIES)
        name = names[description.translation_key]["name"]
        lines.append(f"| {name} | {unit} | {off} | {cells} |")
    return lines


def render() -> str:
    """Return the generated document."""
    lines = [HEADER, *_model_table(), "", "## Entities", ""]
    for platform, title, descriptions in PLATFORMS:
        lines.extend([*_entity_table(platform, title, descriptions), ""])
    return "\n".join(lines)


if __name__ == "__main__":
    OUTPUT.write_text(render())
